spring:
#  profiles:
#    active: dev
  codec:
    max-in-memory-size: 100MB
  kafka.producer.bootstrap-servers: localhost:9092
  kafka.producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
  kafka.producer.value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  
      
server:
  port: 8089



  

